# Generated by Django 4.2.5 on 2025-07-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('available', models.IntegerField(default=0)),
                ('lead_time', models.IntegerField(default=0)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('season_start_date', models.DateField(blank=True, null=True)),
                ('season_end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(related_name='orders', to='orders.product')),
            ],
        ),
    ]
